python_functionality
zoiaivanova/common pull request #3
Opened 2019-10-03 23:45 UTC by zoiaivanova

2019-10-04 08:46 UTC, yuriimchg requested changes
привіт
переглянув дз, 
виглядає шикарно
але є декілька нюансів

2019-10-04 08:46 UTC, yuriimchg commented on python_functionality/homework.py
> +        if student.get('name') is not None:
```suggestion
        if student.get('name'):
```

так також можна)

2019-10-04 08:46 UTC, yuriimchg commented on python_functionality/homework.py
> +            del member[redundant_key]
тут можна заміними `del` на метод словника `remove`
старайся не використовувати `del`, якщо це можливо
детальніше можна почитати тут:
https://stackoverflow.com/a/23331576/8995868

2019-10-04 08:46 UTC, yuriimchg commented on python_functionality/homework.py
> +    if data:
це завдання можна гарно вирішити за допомогою list comprehensions (бажано, але не обов'язково)

2019-10-04 08:46 UTC, yuriimchg commented on python_functionality/homework.py
> +    if data:
чому б `if` перевірку не запхати всередину списку?

2019-10-04 08:46 UTC, yuriimchg commented on python_functionality/homework.py
> +        return min([str(element) for element in data], key=len)
```suggestion
        return min([str(element) for element in data if data], key=len)
```

2019-10-04 08:46 UTC, yuriimchg commented on python_functionality/homework.py
> +    if data:
хоча виглядає так, ніби її й не дуже потрібно

2019-10-04 08:46 UTC, yuriimchg commented on python_functionality/homework.py
> +    return max([item for box in data for item in box])
дуже цікаве рішення
не міг зрозуміти, як воно працює, поки сам не відтворив)

2019-10-04 16:49 UTC, zoiaivanova commented
@yuriimchg дякую за зауваження, змiнила та ще додала параметр у `min` `default=None` вiд себе 😸

2019-10-05 09:57 UTC, yuriimchg approved these changes
переглянув ще раз
все дуже гарно, пайтонічно, функціональненько
:+1:

2019-10-05 14:21 UTC, zoiaivanova commented
@yuriimchg дякую! 🤩

2019-10-07 21:22 UTC, merged